@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

# MESSAGES
### Lists all messages
GET {{baseUrl}}/messages/
?limit=10
&offset=0
Authorization: Bearer {{authToken}}
### List one message
GET {{baseUrl}}/messages/30/
### Create a message
POST {{baseUrl}}/messages/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "De Leo para Joana",
    "deId": 14,
    "paraId": 12
}
### Update a message
PATCH {{baseUrl}}/messages/34/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "De Leo para Joana",
    "lido": false
}
### Delete a message
DELETE {{baseUrl}}/messages/34/
Authorization: Bearer {{authToken}}



# 



# Pessoas
### List all users
GET {{baseUrl}}/users/
?limit=10
&offset=0
Authorization: Bearer {{authToken}}
### List one user
GET {{baseUrl}}/users/14/
Authorization: Bearer {{authToken}}
### Create a user
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "luiz@email.com",
    "password": "123456",
    "nome": "Luiz"
}
### Update a user
PATCH {{baseUrl}}/users/23/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "nome": "aaaaaa"
}
### Delete a user
DELETE {{baseUrl}}/users/16/
Authorization: Bearer {{authToken}}



# 



# AUTH
### Authentication
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "luiz@email.com",
    "password": "123456"
}

#
### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello


### Re-Authentication
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh/
Content-Type: application/json

{
    "refreshToken":"{{refreshToken}}"
}